// Code generated by scripts/generate.mjs from ts/package.json. DO NOT EDIT.

/**
 * Version of the contract this package carries. Consumers log it at
 * startup, since 'which version' is the first question every
 * compatibility bug asks (TZ §3.1).
 */
export const CLOUD_CONTRACT_VERSION = '0.1.0'
